slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: localization 
    map_file_name: /home/mohamed/ros2_ws/src/reactive_controller/resource/new_slam_map
    map_start_pose: [ 0.0, 0.0, 0.0 ]
    map_publisher: true

    scan_topic: /scan
    odom_frame: odom
    base_frame: base_link
    map_frame: map
